name: Build and Release Debug APK

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: '7.7-a2'
        required: true
      release_name:
        description: 'Kotatsu Dev (Debug) v7.7-a2'
        required: false
      is_prerelease:
        description: 'Is this a pre-release?'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2024.10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          draft: false
          prerelease: ${{ github.event.inputs.is_prerelease }}

      - name: Upload releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: debug.apk
          asset_content_type: application/vnd.android.package-archive
