name: Build and Release Debug APK

on:
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2024.10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Debug Release ${{ github.run_number }}
          draft: false
          prerelease: true

      - name: Upload Debug APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: KotatsuDev-debug-${{ github.run_number }}.apk
          asset_content_type: application/vnd.android.package-archive
